import React, {useState, useRef} from "react";
import {
    Modal,
    View,
    Text,
    StyleSheet,
    TouchableOpacity,
    Animated,
    PanResponder,
    Dimensions,
    ScrollView
} from "react-native";

const {height} = Dimensions.get("window");
const MAX_HEIGHT = height * 0.8;

export const TermsPolicyModal = ({visible, onClose, onAgree}) => {
    const [modalHeight, setModalHeight] = useState(new Animated.Value(height / 2));

    const panResponder = useRef(
        PanResponder.create({
            onStartShouldSetPanResponder: () => true,
            onPanResponderMove: (event, gestureState) => {
                const newHeight = height - gestureState.moveY;

                if (newHeight >= height / 2 && newHeight <= MAX_HEIGHT) {
                    setModalHeight(new Animated.Value(newHeight));
                }
            },
            onPanResponderRelease: (event, gestureState) => {
                if (gestureState.dy > 100) {
                    onClose();
                } else if (gestureState.dy < -100) {
                    Animated.spring(modalHeight, {
                        toValue: MAX_HEIGHT,
                        useNativeDriver: false,
                    }).start();
                } else {
                    Animated.spring(modalHeight, {
                        toValue: height / 2,
                        useNativeDriver: false,
                    }).start();
                }
            },
        })
    ).current;

    return (
        <Modal
            visible={visible}
            transparent={true}
            animationType="slide"
        >
            <View style={styles.modalOverlay}>
                <Animated.View
                    style={[styles.modalContainer, {height: modalHeight}]}
                >
                    {/* Draggable Header */}
                    <View {...panResponder.panHandlers} style={styles.draggableArea}>
                        <TouchableOpacity onPress={onClose} style={styles.panResponderButton}>
                            <Text
                                alignText={'center'}
                                style={{margin: 30}}
                            />
                        </TouchableOpacity>
                    </View>

                    {/* Scrollable Content */}
                    <ScrollView contentContainerStyle={styles.scrollViewContent}>
                        <Text style={styles.modalText}>
                            {/* Your Terms and Policy Text Here */}
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                            This is where the terms and policy text will go...
                        </Text>
                    </ScrollView>

                    {/* Agree Button */}
                    <TouchableOpacity style={styles.agreeButton} onPress={onAgree}>
                        <Text style={styles.agreeButtonText}>Agree</Text>
                    </TouchableOpacity>
                </Animated.View>
            </View>
        </Modal>
    );
};

const styles = StyleSheet.create({
    modalOverlay: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContainer: {
        backgroundColor: 'white',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingTop: 20,
        paddingHorizontal: 20,
    },
    draggableArea: {
        width: '100%',
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#ccc',
    },
    panResponderButton: {
        position: 'absolute',
        zIndex: 1,
        height: 4,
        borderRadius: 10,
        backgroundColor: '#5A9AA9',
    },
    scrollViewContent: {
        paddingVertical: 20,
    },
    modalText: {
        fontSize: 16,
        color: '#333',
    },
    agreeButton: {
        marginVertical: 10,
        backgroundColor: '#5A9AA9',
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: 'center',
    },
    agreeButtonText: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
    },
});
